name: new-blog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node: [15]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: yarn install, build
      run: |
        yarn
        yarn build
    - name: Deploy Site
      uses: NickSchimek/deploy_jamstack_action@v1
      with:
         build-dir: dist
         github-token: ${{ secrets.ACCESS_TOKEN }}
         github-actor: ${{ github.actor }}
         github-repo: kilicmu/new-blog

      env:
        CI: true